import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";
import Script from "next/script";
export const metadata = {
  title: "Weblifix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="background_animation">
          <div className="animated_balls"></div>
          <div className="animated_balls"></div>
          <div className="animated_balls"></div>
        </div>
        {children}
        <Script src="https://smtpjs.com/v3/smtp.js"></Script>
      </body>
    </html>
  );
}
