import Navbar from "@/Components/Navbar/Navbar";

import "./globals.css";

export const metadata = {
  title: "Weblifix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="background_animation">
          <div className="animated_balls"></div>
          <div className="animated_balls"></div>
          <div className="animated_balls"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
